#!/usr/bin/env python3
import string


def generate():
    SKELETON = """\
// This code was generated by generate_c_rot13.py
char rot13(char c) {{
	switch(c) {{
{cases}
		default:
			return c;
	}}
}}
"""

    cases = ""

    def generate_case(c):
        return f"""\
		case '{c}':
			return '{chr(((ord(c) - ord("a") + 13) % 26) + ord("a"))}';
"""

    for c in string.ascii_lowercase:
        cases += generate_case(c)

    return SKELETON.format(cases=cases)


if __name__ == "__main__":
    with open("rot13.h", "w") as out_file:
        out_file.write(generate())
