// This code was generated by generate_c_rot13.py
char rot13(char c) {
	switch(c) {
		case 'a':
			return 'n';
		case 'b':
			return 'o';
		case 'c':
			return 'p';
		case 'd':
			return 'q';
		case 'e':
			return 'r';
		case 'f':
			return 's';
		case 'g':
			return 't';
		case 'h':
			return 'u';
		case 'i':
			return 'v';
		case 'j':
			return 'w';
		case 'k':
			return 'x';
		case 'l':
			return 'y';
		case 'm':
			return 'z';
		case 'n':
			return 'a';
		case 'o':
			return 'b';
		case 'p':
			return 'c';
		case 'q':
			return 'd';
		case 'r':
			return 'e';
		case 's':
			return 'f';
		case 't':
			return 'g';
		case 'u':
			return 'h';
		case 'v':
			return 'i';
		case 'w':
			return 'j';
		case 'x':
			return 'k';
		case 'y':
			return 'l';
		case 'z':
			return 'm';

		default:
			return c;
	}
}
